-- show databases;
-- create database arundbex4;
use arundbex4;

CREATE TABLE STUDENTS(SID INT PRIMARY KEY,SNAME VARCHAR(10),BRANCH VARCHAR(10), AGE INT); 
CREATE TABLE FACULTY(FACULTY_ID INT,FACULTY_NAME VARCHAR(20),HIREDATE DATE,SUBJECT VARCHAR(20));
CREATE TABLE STUDENTMARKS(STUDENT_ID INT,STUDENT_NAME CHAR(20),OS INT,JAVA INT,DBMS INT,DM INT,BEFA INT,TOTAL  INT);
CREATE TABLE EMPLOYEE(ENO INT,ENAME VARCHAR(20),JOB CHAR(20),MGRID INT,HIREDATE DATE, SALARY INT,COMMISION INT,DAPRTMENTNO INT);


-- ALTER TABLE 
ALTER TABLE FACULTY ADD ( DEPARTMENT CHAR(10));
DESC  FACULTY;
ALTER TABLE STUDENTMARKS ADD (AVERAGE INT);


-- DROP COLUMNS 
ALTER TABLE  FACULTY DROP COLUMN HIREDATE;
ALTER TABLE STUDENTMARKS DROP COLUMN AVERAGE;
 -- MODIFY COLUMNS -- 
ALTER TABLE EMPLOYEE MODIFY COLUMN SALARY FLOAT(6,2);
ALTER TABLE STUDENTS MODIFY COLUMN BRANCH CHAR(10);

-- RENAME COLUMNS  
RENAME TABLE EMPLOYEE TO EMP;

-- TRUNCAT TABLE 
TRUNCATE TABLE EMP;
 

-- DROP TABLE 
DROP TABLE EMP;




