-- EXPERIMENT – 6
 /* 
Querying (using ANY, ALL, IN, Exists, NOT EXISTS, UNION,  Constraints etc.) 
*/
DROP DATABASE IF EXISTS EXPERIMENT6DB;
CREATE DATABASE EXPERIMENT6DB;
USE EXPERIMENT6DB;

-- crate EMPLOYEE Table
CREATE TABLE EMPLOYEE (
EID VARCHAR(5) PRIMARY KEY,
FIRSTNAME VARCHAR(20),
LASTNAME VARCHAR(20),
JOB VARCHAR(20),
SALARY INT,
ADDRESS VARCHAR(20)
);

-- Insert Values into EMPLOYEE
INSERT INTO EMPLOYEE VALUES
('E01','SRI','RAVI','MANAGER',55000,'CHANDIGARH'),
('E02','ABHI','VARUN','ADMIN',20000,'DELHI'),
('E03','K','NITIN','ASSOCIATE',28000,'PUNE'),
('E04','PETER','ROBIN','ASSOCIATE',28000,'BANGALORE'),
('E05','JOSEPHINE','AMMY','DEVELOPER',38000,'HYDERABAD'); 

-- crate  PROJECT Table
CREATE TABLE PROJECT (
PID VARCHAR(5) PRIMARY KEY,
PNAME VARCHAR(20),
LOCATION VARCHAR(20),
EID VARCHAR(5),
FOREIGN KEY (EID) REFERENCES EMPLOYEE(EID)
); 

-- Insert Values
INSERT INTO PROJECT VALUES
('P1','IOT','BANGALORE','E01'),
('P3','BIG DATA','DELHI','E03'),
('P4','RETAIL','MUMBAI','E04'),
('P2','ANDROID','HYDERABAD','E05');

-- SQL Queries
-- 1. Find employees working on at least one project (ANY) 
SELECT EID, FIRSTNAME, LASTNAME
FROM EMPLOYEE
WHERE EID = ANY
(SELECT EID FROM PROJECT);


-- 2. Find employees working on BIG DATA project (ALL)

SELECT EID, FIRSTNAME, LASTNAME
FROM EMPLOYEE
WHERE EID = ALL
(SELECT EID FROM PROJECT WHERE PNAME='BIG DATA');

-- 3. Employees from Delhi or Hyderabad (IN)
SELECT *
FROM EMPLOYEE
WHERE ADDRESS IN ('DELHI','HYDERABAD');

-- 4. Employees not from Hyderabad (NOT IN)
SELECT *
FROM EMPLOYEE
WHERE ADDRESS NOT IN ('HYDERABAD');

-- 5. Employees working on at least one project (EXISTS)

SELECT EID, FIRSTNAME, LASTNAME
FROM EMPLOYEE
WHERE EXISTS
(SELECT *
 FROM PROJECT
 WHERE EMPLOYEE.EID = PROJECT.EID);
 
 -- 6. Employees not working on any project (NOT EXISTS)
 
 SELECT EID, FIRSTNAME, LASTNAME
FROM EMPLOYEE
WHERE NOT EXISTS
(SELECT *
 FROM PROJECT
 WHERE EMPLOYEE.EID = PROJECT.EID);
 
 -- STUDENT Tables
 CREATE TABLE STUDENT1 (
SID INT,
SNAME VARCHAR(20),
AGE INT,
ADDRESS VARCHAR(20)
);

-- Insert Values
INSERT INTO STUDENT1 VALUES
(100,'Raj',19,'Hyd'),
(101,'Rajesh',19,'Hyd'),
(102,'Ramesh',20,'Hyd'),
(103,'Anvesh',20,'Hyd'),
(104,'Abhinav',20,'TN'),
(105,'Rahul',20,'Bangalore');

-- STUDENT2
CREATE TABLE STUDENT2 (
SID INT,
SNAME VARCHAR(20),
AGE INT,
ADDRESS VARCHAR(20)
);

INSERT INTO STUDENT2 VALUES
(201,'Rahul',18,'Bangalore'),
(202,'John',19,'Bangalore'),
(203,'Joe',20,'Hyd'),
(204,'Alex',20,'Chennai');


-- UNION Operation
-- UNION (removes duplicates)
/* Explanation

UNION → removes duplicate values

UNION ALL → shows duplicate values also*/


SELECT SNAME FROM STUDENT1
UNION
SELECT SNAME FROM STUDENT2; 

-- UNION ALL (includes duplicates)
SELECT SNAME FROM STUDENT1
UNION ALL
SELECT SNAME FROM STUDENT2;
 